application: isufinstudio
version: 2
runtime: python
api_version: 1

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

## CSS
- url: /css
  static_dir: static/css
- url: /css/(.*)
  static_files: static/css/\1
  upload: static/css/(.*)

## cron
- url: /crondata
  script: first.py
  #secure: always
  login: admin

## Main WSGI
- url: .*
  script: map.py
  secure: always
  #login: admin
