application: isufinstudio
version: 1
runtime: python
api_version: 1

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

## cron
- url: /crondata
  script: crondata.py
  #secure: always
  login: admin

## Main WSGI
- url: .*
  #script: first.py
  script: crondata.py
  #secure: always
  #login: admin
